spring.application.name=Lab-Resource-Utilization
spring.datasource.url=jdbc:postgresql://localhost:5432/LabResourceDBm
spring.datasource.username=postgres
spring.datasource.password=Nirbhay
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true