name: Keep Backend Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch: # Allows running manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -sSf https://lab-resource-utilization-platform-t41e.onrender.com/api/auth/login || echo "Failed to ping but workflow continues"
